name: Update README with recent activities

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md with recent activities'
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
