name: Update README with recent activities
run-name: Automated update

on:
  schedule:
    - cron: '0 10,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activities
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: '⚡ Update README with the recent activities'
          MAX_LINES: 10
