name: Update README

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: "⚡ update readme with the recent activity"
          MAX_LINES: 10
