name: user-statistician

on:
  schedule:
    - cron: "0 10,12 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull latest main
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git pull origin main

    - name: Generate the user stats image for Github Profile
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-dimmed
        custom-title: My GitHub Statistics
        max-languages: 100
        animated-language-chart: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
