name: Waka Gist Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-gist:
    name: Update WakaTime Gist
    runs-on: ubuntu-latest
    steps:
      - name: Update Gist with WakaTime stats
        uses: YouEclipse/waka-box@v0.1.8 # Hoặc sử dụng @master, nhưng tag cụ thể ổn định hơn
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          GIST_ID: "115a231cb098cb5d2c033e8f41cbf4fb"
